import type { Metadata } from "next";
import { Poppins, Kalam } from "next/font/google";
import "./globals.css";

import Provider from "./provider";

const kalam = Kalam({
  subsets: ["latin"],
  variable: "--font-kalam",
  weight: ["300", "400", "700"],
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "300", "500", "700", "800"],
});

export const metadata: Metadata = {
  title: "Notes Corner",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${kalam.variable} antialiased`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
